# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trecord', models.CharField(choices=[('P', 'Personal'), ('S', 'Study')], max_length=100)),
                ('category', models.CharField(choices=[('django', 'Django'), ('redes1', 'Redes1'), ('prog3', 'Prog3'), ('arqs', 'Arquitetura de Sistemas'), ('pensamentos', 'Pensamentos')], max_length=100)),
            ],
        ),
    ]
